### ISSUE TITLE
Task 02 -> Create Product Component

### ISSUE THREAD

**Issue by MomoTaheri** [MamadTaheri68/RN-Jupiter-Team#7]
ساخت کامپوننت با عنوان
Product

**Comment by emel95** [comment]
فاز توسعه رو تموم کردم و منتظر داده های سرویس هستم برای اتمام کامپوننت

**Comment by MomoTaheri** [comment]
سلام
حداکثر تا امشب یعنی ساعت 22 سه شنبه 20 اردیبهشت 1401 سرویس نوشته میشه و به شما تحویل داده میشه.
جهت توسعه کار:
شما فرض کنید که قراره یه سرویس رو صدا بزنید و یه آرایه شامل دو عضو رو تحویل بگیرید.
عضو اول یه متغیر با نام  isLoading هست که وضعیت لود شدن داده ها رو برمیگردونه و بصورت boolean هست
عضو دوم یه آرایه هست با نام products که میتونه بین صفر عنصر تا 40 عنصر داشه باشه

**Comment by MomoTaheri** [comment]
Done
